fix build process

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -7,4 +7,7 @@ echo "\n========================================================================
 pnpm -r --no-bail ts:check || { echo "TypeScript check failed: exit code $?" && exit_code=1; }
 echo "\n==========================================================================================================\n"
 
+pnpm -r --no-bail build || { echo "Cannot build: exit code $?" && exit_code=1; }
+echo "\n==========================================================================================================\n"
+
 exit $exit_code
